function cart(){
  const rows=cartRows();const rc=state.remoteCart;const cur=rc?.currency_code||rows[0]?.product?.currency||'SAR';
  const remoteItems=rc?.items||[];
  const findLine=(item)=>remoteItems.find(li=>li.id===item.lineItemId||li.variant_id===item.variantId)||null;
  const localSubtotal=rows.reduce((sum,r)=>sum+parsePrice(r.product.price)*r.item.qty,0);
  const subtotal=Number(rc?.item_subtotal??rc?.subtotal??localSubtotal);
  const discountTotal=Math.abs(Number(rc?.discount_total??0));
  const total=Number(rc?.total??Math.max(0,subtotal-discountTotal));
  const saving=cartSaving()+discountTotal;
  const groups={};rows.forEach(r=>{(groups[r.product.store]??=[]).push(r)});
  const productRow=({item,product:p})=>{const line=findLine(item);const unit=Number(line?.unit_price??line?.subtotal/Math.max(1,Number(line?.quantity||1))??p.variants?.find(v=>v.id===item.variantId)?.priceNumeric??parsePrice(p.price));const oldNumeric=Number(p.variants?.find(v=>v.id===item.variantId)?.originalNumeric??parsePrice(p.old));const discount=oldNumeric>unit?Math.round((1-unit/oldNumeric)*100):0;return `<div class="shopping-item"><div class="shopping-image"><img src="${absoluteProductImage(p.img)}" alt="${esc(p.name)}"></div><div class="shopping-info"><h3>${p.name}</h3><button class="shopping-store" data-action="open-store" data-store="${storesData.find(s=>s.name===p.store)?.id||''}">${p.store}</button><div class="shopping-price"><b>${apiMoneyString(unit,cur)}</b>${oldNumeric>unit?`<s>${apiMoneyString(oldNumeric,cur)}</s><em>خصم ${discount}%</em>`:''}</div><div class="shopping-delivery">${icon('circle-check',14)} متوفر وجاهز للشحن</div><div class="shopping-actions"><div class="quantity-control"><button data-action="cart-minus" data-id="${p.id}">−</button><span>${item.qty}</span><button data-action="cart-plus" data-id="${p.id}">+</button></div><div class="shopping-mini-actions"><button class="danger" data-action="cart-remove" data-id="${p.id}">${icon('trash-2',15)} حذف</button></div></div></div></div>`};
  return `<section class="screen">${simpleHead('حقيبة التسوق')}<div class="page-wrap"><div class="shopping-address"><div class="address-info"><span class="address-pin">${icon('map-pin',20)}</span><div><small>التوصيل إلى</small><strong>${state.activeAddress?`${esc(state.activeAddress.label)} - ${esc(state.activeAddress.area)}`:'اختر عنوان التوصيل'}</strong></div></div><button class="address-change" data-action="open-addresses">تغيير</button></div>
    ${rows.length?`${Object.entries(groups).map(([store,items])=>`<section class="cart-store-group"><div class="cart-store-head"><span>${icon('store',17)}</span><strong>${store}</strong><small>${items.length} منتج</small></div><div class="shopping-products">${items.map(productRow).join('')}</div><div class="cart-store-shipping">${icon('truck',16)} <span>يتم احتساب توصيل هذا المتجر حسب العنوان ومكتب التوصيل.</span></div></section>`).join('')}
      <div class="shopping-note"><button class="shopping-note-head" data-action="toggle-note"><span>إضافة ملاحظة للطلب</span><b>${icon(state.noteOpen?'chevron-up':'chevron-down',18)}</b></button>${state.noteOpen?`<div class="shopping-note-body"><textarea placeholder="اكتب ملاحظتك للبائع أو شركة التوصيل..."></textarea></div>`:''}</div>
      <div class="coupon-box"><div><strong>لديك كوبون؟</strong><small>${state.appliedCoupon?`تم تطبيق ${esc(state.appliedCoupon)}`:'أدخل الكود ثم اضغط تطبيق'}</small></div><div class="coupon-row"><input id="coupon-code" value="${esc(state.appliedCoupon||state.couponCode||'')}" placeholder="مثال SPIKE10"><button data-action="apply-coupon">تطبيق</button></div></div>
      <div class="shopping-invoice"><h2>تفاصيل الفاتورة</h2><div class="invoice-line"><span>إجمالي المنتجات</span><b>${apiMoneyString(subtotal,cur)}</b></div>${discountTotal?`<div class="invoice-line"><span>خصم الكوبون</span><b>- ${apiMoneyString(discountTotal,cur)}</b></div>`:''}<div class="invoice-total"><span>المجموع</span><strong>${apiMoneyString(total,cur)}</strong></div>${saving>0?`<div class="saving-message">${icon('circle-check',16)} أنت وفّرت ${apiMoneyString(saving,cur)}</div>`:''}</div><div class="shopping-footer"><button class="shopping-checkout" data-nav="checkout">متابعة إلى الدفع <span>•</span> ${apiMoneyString(total,cur)}</button></div>`:`<div class="empty-state rich-empty">${icon('shopping-bag',38)}<strong>حقيبة التسوق فارغة</strong><span>أضف منتجاتك المفضلة وارجع هنا لإتمام الطلب.</span><button class="red-action" data-nav="home">ابدأ التسوق</button></div>`}</div></section>${bottom('cart')}`
}
