function orders(){
  let list=state.ordersTab==='previous'?previousOrders:currentOrders;
  if(state.orderStatusFilter!=='الكل')list=list.filter(o=>o.status===state.orderStatusFilter);
  return `<section class="screen">${simpleHead('طلباتي')}<div class="page-wrap">
    <div class="orders-toolbar"><div class="orders-tabs"><button class="order-tab ${state.ordersTab==='current'?'active':''}" data-action="orders-current">الحالية</button><button class="order-tab ${state.ordersTab==='previous'?'active':''}" data-action="orders-previous">السابقة</button></div><button class="orders-filter" data-action="orders-filter">⌯</button></div>
    <div class="orders-list">${list.length?list.map(order=>`<button class="storm-order-card" data-action="open-order" data-order="${order.id}"><div class="storm-order-top"><div class="order-status-wrap"><span class="order-status ${order.status==='تم التوصيل'?'delivered':''} ${order.status==='ملغي'?'cancelled':''}">${order.status}</span><small>${order.date}</small></div><span class="order-number">#${order.id}</span></div><div class="storm-order-product"><img src="${A}${order.image}"><div class="order-product-info"><strong>${order.product}</strong><span>${order.store}</span><b>${order.price}</b></div><span class="order-open-arrow">${icon('arrow-left',21)}</span></div></button>`).join(''):`<div class="empty-state"><strong>لا توجد طلبات مطابقة</strong><span>جرّب تغيير الفلتر أو اختيار تبويب آخر.</span></div>`}</div>
  </div>${ordersFilterSheet()}</section>${bottom('profile')}`
}

function ordersFilterSheet(){const statuses=['الكل','قيد التجهيز','تم التأكيد','تم الشحن','تم التوصيل','ملغي','مرتجع'];const dates=['اليوم','آخر 7 أيام','آخر 30 يوم','آخر 3 أشهر'];return `<div class="shade ${state.ordersFilter?'show':''}" data-action="close-orders-filter"></div><div class="orders-filter-sheet ${state.ordersFilter?'show':''}"><button class="close-filter icon-button" data-action="close-orders-filter">${icon('x',20)}</button><div class="orders-filter-head"><h3>فلترة الطلبات</h3><button data-action="reset-orders-filter">مسح الكل</button></div><div class="filter-group"><h4>الفترة الزمنية</h4><div class="filter-chips">${dates.map(d=>`<button class="filter-chip ${state.orderDateFilter===d?'selected':''}" data-action="select-order-date" data-value="${d}">${d}</button>`).join('')}</div></div><div class="filter-group"><h4>حالة الطلب</h4><div class="filter-chips">${statuses.map(s=>`<button class="filter-chip ${state.orderStatusFilter===s?'selected':''}" data-action="select-order-status" data-value="${s}">${s}</button>`).join('')}</div></div><button class="red-action full" data-action="apply-orders-filter">تطبيق الفلتر</button></div>`}

function orderDetails(){const all=[...currentOrders,...previousOrders];const order=all.find(o=>o.id===state.selectedOrder)||currentOrders[0];return `<section class="screen">${simpleHead('تفاصيل الطلب')}<div class="page-wrap">
  <div class="order-detail-card order-summary"><div class="detail-head"><div><small>رقم الطلب</small><strong>#${order.id}</strong></div><span class="order-status ${order.status==='تم التوصيل'?'delivered':''}">${order.status}</span></div><div class="detail-product"><img src="${A}${order.image}"><div><strong>${order.product}</strong><span>الكمية: 1</span><b>${order.price}</b></div></div></div>
  <div class="order-detail-card"><h3 class="detail-title">حالة الطلب</h3><div class="storm-timeline"><div class="timeline-step done"><i>${icon('check',16)}</i><div><strong>تم التأكيد</strong><small>تم تأكيد طلبك</small></div></div><span class="timeline-line"></span><div class="timeline-step active"><i>2</i><div><strong>قيد التجهيز</strong><small>البائع يجهز طلبك الآن</small></div></div><span class="timeline-line"></span><div class="timeline-step"><i>3</i><div><strong>تم الشحن</strong><small>سيتم تسليم الطلب لشركة الشحن</small></div></div><span class="timeline-line"></span><div class="timeline-step"><i>4</i><div><strong>تم التوصيل</strong><small>يصل الطلب إلى عنوانك</small></div></div></div></div>
  <div class="order-detail-card"><h3 class="detail-title">بيانات التوصيل</h3><div class="detail-row"><span>رقم الجوال</span><b>777277779</b></div><div class="detail-row"><span>عنوان التوصيل</span><b>صنعاء - الأصبحي</b></div></div>
  <div class="order-detail-card"><h3 class="detail-title">تفاصيل الفاتورة</h3><div class="detail-row"><span>إجمالي المنتجات</span><b>$75.45</b></div><div class="detail-row"><span>رسوم الشحن</span><b>$5.00</b></div><div class="detail-row total-detail"><span>الإجمالي</span><b>$80.45</b></div><div class="detail-row"><span>طريقة الدفع</span><b>حوالة مالية</b></div></div>
  <div class="order-detail-card"><h3 class="detail-title">معلومات الطلب</h3><div class="detail-row"><span>تاريخ الطلب</span><b>${order.date}</b></div><button class="invoice-btn" data-action="invoice">الحصول على الفاتورة</button></div>
  <button class="red-action full reorder-btn" data-action="reorder">إعادة الطلب</button>
  </div></section>${bottom('profile')}`}
