function stores(){
  let list=storesData.slice();
  if(state.storesSearch)list=list.filter(s=>s.name.includes(state.storesSearch)||s.category.includes(state.storesSearch));
  if(state.storesCategory!=='الكل')list=list.filter(s=>s.category===state.storesCategory);
  if(state.storesMinRating>0)list=list.filter(s=>Number(s.rating)>=state.storesMinRating);
  if(state.storesSort==='rating')list.sort((a,b)=>Number(b.rating)-Number(a.rating));
  if(state.storesSort==='reviews')list.sort((a,b)=>Number(b.reviews)-Number(a.reviews));
  if(state.storesSort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'ar'));
  return `<section class="screen">${simpleHead('المتاجر',{sortAction:'stores-sort'})}<div class="page-wrap"><div class="searchbox store-search">${icon('search',20,'search-lucide')}<input data-action="store-search" value="${esc(state.storesSearch)}" placeholder="البحث عن متجر"></div><div class="store-list">${list.map(store=>`<button class="store-showcase" data-action="open-store" data-store="${store.id}"><div class="store-cover"><img src="${absoluteProductImage(store.banner)}"><span class="store-rating"><span class="filled-rating-star">${icon('star',14)}</span>${store.rating} <small>(${store.reviews})</small></span></div><div class="store-showcase-footer"><div class="store-logo-badge">${store.logo?`<img src="${absoluteProductImage(store.logo)}" alt="${esc(store.name)}">`:esc(store.logoText)}</div><div><strong>${store.name}</strong><span>${store.category}</span></div><b>←</b></div></button>`).join('')}${!list.length?'<div class="empty-ux">لا توجد متاجر مطابقة للفلتر</div>':''}</div></div>${storesFilterSheet()}${storesSortSheet()}</section>${bottom('profile')}`
}

function storesFilterSheet(){const ratings=[['0','كل التقييمات'],['4','4 نجوم فأعلى'],['4.5','4.5 نجوم فأعلى']];return `<div class="shade ${state.storesFilterSheet?'show':''}" data-action="close-stores-filter"></div><div class="store-sheet ${state.storesFilterSheet?'show':''}"><button class="close-filter icon-button" data-action="close-stores-filter">${icon('x',20)}</button><h3>فلترة المتاجر</h3><p>التقييم</p><div class="sort-options">${ratings.map(([v,l])=>`<label><span>${l}</span><input type="radio" name="stores-rating" value="${v}" ${String(state.storesMinRating)===v?'checked':''}></label>`).join('')}</div><button class="red-action full" data-action="apply-stores-filter">تطبيق الفلتر</button></div>`}

function storesSortSheet(){const options=[['relevance','الأكثر صلة'],['rating','الأعلى تقييماً'],['reviews','الأكثر مراجعات'],['name','الاسم أبجدياً']];return `<div class="shade ${state.storesSortSheet?'show':''}" data-action="close-stores-sort"></div><div class="store-sheet ${state.storesSortSheet?'show':''}"><button class="close-filter icon-button" data-action="close-stores-sort">${icon('x',20)}</button><h3>الترتيب حسب</h3><div class="sort-options">${options.map(([v,l])=>`<label><span>${l}</span><input type="radio" name="stores-sort" value="${v}" ${state.storesSort===v?'checked':''}></label>`).join('')}</div></div>`}

function storeDetails(){
  const store=getStore(state.selectedStore);let list=store.products.map(getProduct).filter(Boolean);
  if(state.storeProductSearch)list=list.filter(p=>p.name.includes(state.storeProductSearch)||p.category.includes(state.storeProductSearch));
  if(state.storeCategory!=='الكل')list=list.filter(p=>p.category===state.storeCategory);
  if(state.storeSort==='price-low')list.sort((a,b)=>parsePrice(a.price)-parsePrice(b.price));
  if(state.storeSort==='price-high')list.sort((a,b)=>parsePrice(b.price)-parsePrice(a.price));
  if(state.storeSort==='rating')list.sort((a,b)=>Number(b.rating)-Number(a.rating));
  const followed=state.followedStores.has(store.id);
  return `<section class="screen store-detail-screen">${status()}<div class="store-detail-top"><button class="back-btn icon-button" data-action="back">${icon('arrow-right',23)}</button><div class="searchbox store-detail-search">${icon('search',20,'search-lucide')}<input data-action="store-product-search" value="${esc(state.storeProductSearch)}" placeholder="ابحث داخل ${store.name}"></div></div>
  <div class="store-hero"><img src="${absoluteProductImage(store.banner)}"><div class="store-profile"><div class="store-profile-logo">${store.logo?`<img src="${absoluteProductImage(store.logo)}" alt="${esc(store.name)}">`:esc(store.logoText)}</div><div><strong>${store.name}</strong><span>${store.category}</span><small>متجر موثوق على Spike</small></div><div class="store-profile-rating"><span class="filled-rating-star">${icon('star',14)}</span>${store.rating} <small>(${store.reviews})</small></div></div><div class="store-summary"><span><b>${store.products.length}</b><small>منتجات</small></span><span><b>${store.reviews}</b><small>مراجعات</small></span><span><b>${store.rating}</b><small>التقييم</small></span></div><button class="store-follow-btn ${followed?'active':''}" data-action="toggle-follow-store" data-store="${store.id}">${icon(followed?'check':'plus',18)} ${followed?'متابَع':'متابعة المتجر'}</button></div>
  <div class="store-controls"><button data-action="store-filter">${icon('sliders-horizontal',17)}<span>فلتر</span></button><button data-action="store-sort">${icon('arrow-up-down',17)}<span>ترتيب</span></button></div><div class="page-wrap"><div class="store-products-heading"><h2>منتجات المتجر</h2><span>${list.length} منتج</span></div><div class="product-grid">${list.map(card).join('')}</div>${!list.length?`<div class="empty-state rich-empty">${icon('package-search',34)}<strong>لا توجد منتجات مطابقة</strong><span>غيّر الفلتر أو جرّب كلمة بحث مختلفة.</span></div>`:''}</div>${storeFilterSheet()}${storeSortSheet()}</section>${bottom('home')}`
}

function storeFilterSheet(){const cats=['الكل',...categories.map(c=>c[1])];return `<div class="shade ${state.storeFilter?'show':''}" data-action="close-store-filter"></div><div class="store-sheet ${state.storeFilter?'show':''}"><button class="close-filter icon-button" data-action="close-store-filter">${icon('x',20)}</button><h3>فلترة المنتجات</h3><p>القسم</p><div class="filter-chips">${cats.map(c=>`<button class="filter-chip ${state.storeCategory===c?'selected':''}" data-action="store-category" data-value="${c}">${c}</button>`).join('')}</div><button class="red-action full" data-action="apply-store-filter">تطبيق الفلتر</button></div>`}

function storeSortSheet(){const options=[['relevance','الأكثر صلة'],['price-low','السعر: من الأقل للأعلى'],['price-high','السعر: من الأعلى للأقل'],['rating','الأعلى تقييماً']];return `<div class="shade ${state.storeSortSheet?'show':''}" data-action="close-store-sort"></div><div class="store-sheet ${state.storeSortSheet?'show':''}"><button class="close-filter icon-button" data-action="close-store-sort">${icon('x',20)}</button><h3>الترتيب حسب</h3><div class="sort-options">${options.map(([v,l])=>`<label><span>${l}</span><input type="radio" name="store-sort" value="${v}" ${state.storeSort===v?'checked':''}></label>`).join('')}</div></div>`}
