function card(p){
  const fav=state.favs.has(p.id),gallery=(p.images&&p.images.length?p.images:[p.img]);
  const priced=(p.variants||[]).filter(v=>Number(v.priceNumeric)>0).sort((a,b)=>a.priceNumeric-b.priceNumeric)[0];
  const current=Number(priced?.priceNumeric??p.priceNumeric??productPriceAmount(p)??0),old=Number(priced?.originalNumeric??p.originalNumeric??productOldPriceAmount(p)??0),currency=priced?.currency||p.currency||'USD';
  const discount=old>current&&current>0?Math.round((1-current/old)*100):0,galleryControls=gallery.length>1?`<div class="card-gallery-dots">${gallery.map((_,i)=>`<i class="${i===0?'active':''}"></i>`).join('')}</div>`:'',storeRecord=storesData.find(s=>s.name===p.store)||null,purchasable=!!(p.offerId||p.variants?.some(v=>v.offerId));
  const avg=Number(p.review_average??p.reviewAverage??p.rating??0),reviewCount=Number(p.review_count??p.reviewCount??0),ratingText=avg>0?avg.toFixed(1):'جديد';
  const priceHtml=current>0?(old>current?`<div class="sale"><b class="sale-price">${apiMoneyString(current,currency)}</b><span class="old">${apiMoneyString(old,currency)}</span></div>`:`<div class="price">${apiMoneyString(current,currency)}</div>`):`<div class="price">${purchasable?'السعر غير متاح':'غير متاح حالياً'}</div>`;
  return `<article class="product-card" data-product="${p.id}"><div class="product-image card-gallery" data-gallery="${gallery.map(x=>encodeURIComponent(x)).join('|')}" data-gallery-index="0"><button class="fav ${fav?'active':''}" data-action="fav" data-id="${p.id}">${icon('heart',19)}</button>${discount?`<span class="discount-badge">-${discount}%</span>`:''}<img class="card-gallery-img" src="${absoluteProductImage(gallery[0])}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='${A}placeholder-product.svg'">${galleryControls}<button class="plus icon-button" data-action="add" data-id="${p.id}" ${!purchasable?'disabled':''}>${icon('plus',20)}</button></div><div class="pname">${p.name}</div>${priceHtml}<div class="meta"><span class="rating-line filled-rating-star">${icon('star',15)} <b>${ratingText}</b>${reviewCount?` <small>(${reviewCount})</small>`:''}</span><button class="card-store-link" data-action="open-store" data-store="${storeRecord?.id||''}">${p.store}</button></div></article>`;
}
