/* Spike API compatibility layer — legacy Mercur/Medusa network calls disabled. */
const SPIKE_API={baseUrl:'http://localhost:9100/api/v1',timeoutMs:12000};
function storageGet(k){try{return localStorage.getItem(k)||''}catch(_){return ''}}function storageSet(k,v){try{v?localStorage.setItem(k,String(v)):localStorage.removeItem(k)}catch(_){}}
function apiPublishableKey(){return ''}function setApiPublishableKey(){}function customerToken(){return storageGet('spike_customer_token')}function setCustomerToken(t){storageSet('spike_customer_token',t)}function remoteCartId(){return ''}function setRemoteCartId(){}
function apiHeaders({auth=false,json=false}={}){const h={accept:'application/json'};if(json)h['content-type']='application/json';if(auth&&customerToken())h.authorization=`Bearer ${customerToken()}`;return h}
async function apiRequest(path,{method='GET',body,auth=false,allow404=false}={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),SPIKE_API.timeoutMs);try{const p=String(path||'').replace(/^\/api\/v1/,'');const r=await fetch(SPIKE_API.baseUrl+p,{method,headers:apiHeaders({auth,json:body!==undefined}),body:body===undefined?undefined:JSON.stringify(body),signal:ctl.signal});if(allow404&&r.status===404)return null;const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch(_){d={raw:text}}if(!r.ok){const e=new Error(d.message||`HTTP_${r.status}`);e.status=r.status;e.data=d;throw e}return d}finally{clearTimeout(timer)}}async function apiOptional(path,o={}){try{return await apiRequest(path,{...o,allow404:true})}catch(_){return null}}
function absoluteProductImage(src){if(!src)return `${A}placeholder-product.svg`;const v=String(src).trim();if(/^https?:\/\//i.test(v)||v.startsWith('data:')||v.startsWith('blob:'))return v;if(v.startsWith('/uploads/'))return `${SPIKE_API.baseUrl}${v}`;return `${A}${v.replace(/^assets\//,'')}`}
function apiMoneyString(amount,currency='USD'){const n=Number(amount);if(!Number.isFinite(n))return '$0.00';const c=String(currency||'USD').toUpperCase();if(c==='USD')return `$${n.toFixed(2)}`;if(c==='SAR')return `${n.toFixed(2)} ر.س`;if(c.startsWith('YER'))return `${Math.round(n)} ر.ي`;return `${n.toFixed(2)} ${c}`}
/* Old function names remain only as no-network compatibility shims. */
async function fetchMercurRegions(){return []}async function fetchMercurCurrencies(){return []}async function fetchMercurRegion(){return null}async function fetchMercurCategories(){return []}async function fetchMercurCollections(){return []}async function fetchMercurTags(){return []}async function fetchMercurProducts(){return []}async function fetchMercurOffers(){return []}async function fetchMercurSellers(){return []}async function fetchSpikeContent(){return {}}async function fetchProductReviews(){return []}
async function syncMercurAll(){return typeof refreshCatalog==='function'?refreshCatalog():[]}async function syncMercurProducts(){return typeof refreshCatalog==='function'?refreshCatalog():[]}async function syncMercurCustomer(){return null}async function syncMercurCart(){return null}async function syncMercurOrders(){return []}async function syncMercurNotifications(){return []}
